version: "3"
services:
  backend:
    container_name: test-product-fpm
    build: .docker/php/fpm
    restart: always
    working_dir: /app
    volumes:
    - ./.docker/php/fpm/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini
    - .:/app

  webserver:
    restart: always
    container_name: test-product-web
    image: nginx:alpine
    working_dir: /app
    ports:
    - "80:80"
    volumes:
    - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/app:cached
    links:
    - backend